In [1]:
import pandas as pd

In [2]:
data_2019 = pd.read_csv('result_data/data_2019.csv')
data_2019

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,Month
0,107,2019-04-01 07:48:04.7540,2019-04-01 07:49:52.3590,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29536,Subscriber,1966,1,April 2019
1,493,2019-04-01 12:41:09.6540,2019-04-01 12:49:23.0290,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,26191,Customer,1990,1,April 2019
2,512,2019-04-01 14:27:07.9400,2019-04-01 14:35:40.9370,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29302,Subscriber,1987,2,April 2019
3,196,2019-04-01 15:07:38.1510,2019-04-01 15:10:54.6260,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,26220,Subscriber,1989,1,April 2019
4,463,2019-04-01 16:19:24.6940,2019-04-01 16:27:08.6450,3183,Exchange Place,40.716247,-74.033459,3273,Manila & 1st,40.721651,-74.042884,26228,Subscriber,1995,1,April 2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108616,639,2019-06-30 23:38:29.5450,2019-06-30 23:49:09.2110,3677,Glenwood Ave,40.727551,-74.071061,3191,Union St,40.718211,-74.083639,29197,Customer,1986,1,June 2019
108617,643,2019-06-30 23:38:34.9100,2019-06-30 23:49:17.9690,3677,Glenwood Ave,40.727551,-74.071061,3191,Union St,40.718211,-74.083639,26262,Customer,1990,2,June 2019
108618,418,2019-06-30 23:42:30.9400,2019-06-30 23:49:29.5360,3679,Bergen Ave,40.722104,-74.071455,3191,Union St,40.718211,-74.083639,29241,Subscriber,1979,1,June 2019
108619,2529,2019-06-30 23:46:17.5700,2019-07-01 00:28:27.1710,3185,City Hall,40.717732,-74.043845,3213,Van Vorst Park,40.718489,-74.047727,26254,Subscriber,1982,1,June 2019
108620,831,2019-06-30 23:49:01.6830,2019-07-01 00:02:53.1150,3210,Pershing Field,40.742677,-74.051789,3186,Grove St PATH,40.719586,-74.043117,29551,Subscriber,1988,1,June 2019

In [3]:
data_2020 = pd.read_csv('result_data/data_2020.csv')
data_2020

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,Month
0,1437,2020-04-01 01:06:20.6300,2020-04-01 01:30:17.9680,3678,Fairmount Ave,40.725726,-74.071959,3678,Fairmount Ave,40.725726,-74.071959,42314,Customer,2002,2,April 2020
1,264,2020-04-01 05:02:42.0570,2020-04-01 05:07:06.1260,3207,Oakland Ave,40.737604,-74.052478,3195,Sip Ave,40.730897,-74.063913,42146,Subscriber,1963,2,April 2020
2,254,2020-04-01 06:20:28.1190,2020-04-01 06:24:42.1380,3678,Fairmount Ave,40.725726,-74.071959,3195,Sip Ave,40.730897,-74.063913,42255,Subscriber,1981,1,April 2020
3,429,2020-04-01 06:33:30.5170,2020-04-01 06:40:40.1990,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42529,Subscriber,1964,1,April 2020
4,805,2020-04-01 06:38:32.9220,2020-04-01 06:51:58.2050,3193,Lincoln Park,40.724605,-74.078406,3195,Sip Ave,40.730897,-74.063913,42362,Subscriber,1965,1,April 2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71261,2828,2020-06-30 23:53:19.7380,2020-07-01 00:40:28.5760,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,18351,Customer,1969,0,June 2020
71262,2729,2020-06-30 23:54:44.0100,2020-07-01 00:40:13.6470,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,44401,Customer,1969,0,June 2020
71263,2788,2020-06-30 23:54:52.1920,2020-07-01 00:41:20.6500,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42334,Customer,1969,0,June 2020
71264,2702,2020-06-30 23:56:14.6650,2020-07-01 00:41:16.7820,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42463,Customer,1969,0,June 2020
71265,2649,2020-06-30 23:57:46.1490,2020-07-01 00:41:55.5060,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42468,Customer,1998,2,June 2020

In [4]:
total_merged_data = pd.concat([data_2020,data_2019],ignore_index=True)
total_merged_data

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,Month
0,1437,2020-04-01 01:06:20.6300,2020-04-01 01:30:17.9680,3678,Fairmount Ave,40.725726,-74.071959,3678,Fairmount Ave,40.725726,-74.071959,42314,Customer,2002,2,April 2020
1,264,2020-04-01 05:02:42.0570,2020-04-01 05:07:06.1260,3207,Oakland Ave,40.737604,-74.052478,3195,Sip Ave,40.730897,-74.063913,42146,Subscriber,1963,2,April 2020
2,254,2020-04-01 06:20:28.1190,2020-04-01 06:24:42.1380,3678,Fairmount Ave,40.725726,-74.071959,3195,Sip Ave,40.730897,-74.063913,42255,Subscriber,1981,1,April 2020
3,429,2020-04-01 06:33:30.5170,2020-04-01 06:40:40.1990,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42529,Subscriber,1964,1,April 2020
4,805,2020-04-01 06:38:32.9220,2020-04-01 06:51:58.2050,3193,Lincoln Park,40.724605,-74.078406,3195,Sip Ave,40.730897,-74.063913,42362,Subscriber,1965,1,April 2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179882,639,2019-06-30 23:38:29.5450,2019-06-30 23:49:09.2110,3677,Glenwood Ave,40.727551,-74.071061,3191,Union St,40.718211,-74.083639,29197,Customer,1986,1,June 2019
179883,643,2019-06-30 23:38:34.9100,2019-06-30 23:49:17.9690,3677,Glenwood Ave,40.727551,-74.071061,3191,Union St,40.718211,-74.083639,26262,Customer,1990,2,June 2019
179884,418,2019-06-30 23:42:30.9400,2019-06-30 23:49:29.5360,3679,Bergen Ave,40.722104,-74.071455,3191,Union St,40.718211,-74.083639,29241,Subscriber,1979,1,June 2019
179885,2529,2019-06-30 23:46:17.5700,2019-07-01 00:28:27.1710,3185,City Hall,40.717732,-74.043845,3213,Van Vorst Park,40.718489,-74.047727,26254,Subscriber,1982,1,June 2019
179886,831,2019-06-30 23:49:01.6830,2019-07-01 00:02:53.1150,3210,Pershing Field,40.742677,-74.051789,3186,Grove St PATH,40.719586,-74.043117,29551,Subscriber,1988,1,June 2019

In [5]:
total_merged_data.to_csv('result_data/total_merged_data.csv', index=False)